spring:
  data:
    mongodb:
      database: test
      host: mongodb-test
      port: 27019
server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs.json
  swagger-ui:
    path: /swagger
    operations-sorter: alpha
    tags-sorter: alpha

logging:
  level:
    org.springframework.*: warn
    org.hibernate.*: warn
    com.zaxxer.*: warn
    org.mongodb.*: warn

